CREATE TABLE tb_email_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR(255) NOT NULL,
    recipient VARCHAR(320) NOT NULL,
    module VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    error_message VARCHAR(2000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_email_log_created_at ON tb_email_log(created_at DESC, id DESC);

UPDATE tb_position
SET is_locked = TRUE
WHERE LOWER(TRIM(name)) = 'compras';
