CREATE TABLE tb_trello_integration_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number BIGINT NOT NULL,
    order_type VARCHAR(100) NOT NULL,
    client VARCHAR(255) NOT NULL,
    product_code VARCHAR(100) NOT NULL,
    product_description VARCHAR(1000) NOT NULL,
    quantity NUMERIC(15, 3) NOT NULL,
    seller VARCHAR(255) NOT NULL,
    release_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expected_delivery DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    imported_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    destination_email VARCHAR(320) NOT NULL,
    cc_email VARCHAR(320),
    sent_at TIMESTAMP WITHOUT TIME ZONE,
    last_resent_at TIMESTAMP WITHOUT TIME ZONE,
    error_message VARCHAR(2000),
    CONSTRAINT uk_trello_integration_order_product UNIQUE (order_number, product_code)
);

CREATE INDEX idx_trello_integration_record_imported_at
    ON tb_trello_integration_record (imported_at);

CREATE INDEX idx_trello_integration_record_status
    ON tb_trello_integration_record (status);

INSERT INTO tb_param (name, content)
SELECT 'trello.integration.retention-days', '90'
WHERE NOT EXISTS (SELECT 1 FROM tb_param WHERE name = 'trello.integration.retention-days');

INSERT INTO tb_param (name, content)
SELECT 'trello.integration.erp-lookback-days', '7'
WHERE NOT EXISTS (SELECT 1 FROM tb_param WHERE name = 'trello.integration.erp-lookback-days');

INSERT INTO tb_param (name, content)
SELECT 'trello.integration.destination-email', ''
WHERE NOT EXISTS (SELECT 1 FROM tb_param WHERE name = 'trello.integration.destination-email');

INSERT INTO tb_param (name, content)
SELECT 'trello.integration.cc-email', ''
WHERE NOT EXISTS (SELECT 1 FROM tb_param WHERE name = 'trello.integration.cc-email');

INSERT INTO tb_role (authority, title, title_url, parent, parent_url, activated)
SELECT 'ROLE_TRELLO_INTEGRATION', 'Integração Trello', '/trello-integration', 'Engenharia', '/engineering', TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM tb_role WHERE authority = 'ROLE_TRELLO_INTEGRATION'
);

INSERT INTO tb_role (authority, title, parent, parent_url, father_id, activated)
SELECT 'ROLE_TRELLO_INTEGRATION_ADMIN', 'Administrador', 'Engenharia', '/engineering', parent_role.id, TRUE
FROM tb_role parent_role
WHERE parent_role.authority = 'ROLE_TRELLO_INTEGRATION'
  AND NOT EXISTS (
      SELECT 1 FROM tb_role WHERE authority = 'ROLE_TRELLO_INTEGRATION_ADMIN'
  );
