INSERT INTO tb_role (authority, title, title_url, parent, parent_url, activated)
SELECT 'ROLE_CHECKLIST', 'Checklist', '/checklist', 'Qualidade', '/qualidade', TRUE
WHERE NOT EXISTS (SELECT 1 FROM tb_role WHERE authority = 'ROLE_CHECKLIST');

INSERT INTO tb_role (authority, title, parent, parent_url, father_id, activated)
SELECT 'ROLE_CHECKLIST_ADMIN', 'Administrador', 'Qualidade', '/qualidade', parent_role.id, TRUE
FROM tb_role parent_role WHERE parent_role.authority = 'ROLE_CHECKLIST'
AND NOT EXISTS (SELECT 1 FROM tb_role WHERE authority = 'ROLE_CHECKLIST_ADMIN');

INSERT INTO tb_role (authority, title, parent, parent_url, father_id, activated)
SELECT 'ROLE_CHECKLIST_OPERATOR', 'Operador', 'Qualidade', '/qualidade', parent_role.id, TRUE
FROM tb_role parent_role WHERE parent_role.authority = 'ROLE_CHECKLIST'
AND NOT EXISTS (SELECT 1 FROM tb_role WHERE authority = 'ROLE_CHECKLIST_OPERATOR');

INSERT INTO tb_role (authority, title, parent, parent_url, father_id, activated)
SELECT 'ROLE_CHECKLIST_CONSULTATION', 'Consulta', 'Qualidade', '/qualidade', parent_role.id, TRUE
FROM tb_role parent_role WHERE parent_role.authority = 'ROLE_CHECKLIST'
AND NOT EXISTS (SELECT 1 FROM tb_role WHERE authority = 'ROLE_CHECKLIST_CONSULTATION');

CREATE TABLE tb_checklist_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    integration VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deactivation_reason TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    logo BOOLEAN NOT NULL DEFAULT TRUE,
    re_label VARCHAR(120),
    reference_label VARCHAR(120),
    document_title VARCHAR(255) NOT NULL,
    client_nok_history BOOLEAN NOT NULL DEFAULT TRUE,
    dates BOOLEAN NOT NULL DEFAULT FALSE,
    departments BOOLEAN NOT NULL DEFAULT TRUE,
    serial_required BOOLEAN NOT NULL DEFAULT TRUE,
    erp_required BOOLEAN NOT NULL DEFAULT TRUE,
    fields_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_checklist_category_name UNIQUE (name),
    CONSTRAINT ck_checklist_category_integration CHECK (integration IN ('PRODUCTION', 'FIVE_S', 'NONE')),
    CONSTRAINT ck_checklist_category_active_reason CHECK (active OR deactivation_reason IS NOT NULL)
);

CREATE TABLE tb_checklist_category_access (
    category_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (category_id, user_id),
    CONSTRAINT fk_checklist_access_category FOREIGN KEY (category_id) REFERENCES tb_checklist_category ON DELETE CASCADE,
    CONSTRAINT fk_checklist_access_user FOREIGN KEY (user_id) REFERENCES tb_user ON DELETE CASCADE
);

CREATE TABLE tb_checklist_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abbreviation VARCHAR(30) NOT NULL,
    name VARCHAR(160) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_checklist_equipment_abbreviation UNIQUE (abbreviation)
);

CREATE TABLE tb_checklist_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    equipment_id BIGINT,
    predecessor_id BIGINT,
    name VARCHAR(160) NOT NULL,
    title_expression VARCHAR(500) NOT NULL,
    sections_json TEXT NOT NULL,
    signature BOOLEAN NOT NULL DEFAULT FALSE,
    automatic BOOLEAN NOT NULL DEFAULT FALSE,
    version INTEGER NOT NULL DEFAULT 1,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_template_category FOREIGN KEY (category_id) REFERENCES tb_checklist_category,
    CONSTRAINT fk_checklist_template_equipment FOREIGN KEY (equipment_id) REFERENCES tb_checklist_equipment,
    CONSTRAINT fk_checklist_template_predecessor FOREIGN KEY (predecessor_id) REFERENCES tb_checklist_template,
    CONSTRAINT uk_checklist_template_equipment_category UNIQUE (category_id, equipment_id),
    CONSTRAINT uk_checklist_template_predecessor UNIQUE (predecessor_id),
    CONSTRAINT ck_checklist_template_self_reference CHECK (predecessor_id IS NULL OR predecessor_id <> id)
);

CREATE TABLE tb_checklist_flow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number VARCHAR(120),
    normalized_serial VARCHAR(120),
    order_number VARCHAR(60),
    client_id VARCHAR(120),
    client_name VARCHAR(255),
    commercial_item VARCHAR(120),
    salesperson VARCHAR(160),
    plan_json TEXT NOT NULL,
    skipped_json TEXT NOT NULL DEFAULT '{}',
    cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    cancellation_reason TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_checklist_flow_serial UNIQUE (normalized_serial),
    CONSTRAINT ck_checklist_flow_cancel_reason CHECK (NOT cancelled OR cancellation_reason IS NOT NULL)
);

CREATE TABLE tb_checklist_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL,
    creator_id BIGINT NOT NULL,
    owner_id BIGINT,
    finisher_id BIGINT,
    status VARCHAR(20) NOT NULL,
    automatic BOOLEAN NOT NULL DEFAULT FALSE,
    answers_json TEXT NOT NULL DEFAULT '{}',
    fields_json TEXT NOT NULL DEFAULT '{}',
    departments_json TEXT NOT NULL DEFAULT '[]',
    signature VARCHAR(255),
    signed_at TIMESTAMP WITHOUT TIME ZONE,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lock_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_checklist_record_flow FOREIGN KEY (flow_id) REFERENCES tb_checklist_flow,
    CONSTRAINT fk_checklist_record_template FOREIGN KEY (template_id) REFERENCES tb_checklist_template,
    CONSTRAINT fk_checklist_record_creator FOREIGN KEY (creator_id) REFERENCES tb_user,
    CONSTRAINT fk_checklist_record_owner FOREIGN KEY (owner_id) REFERENCES tb_user,
    CONSTRAINT fk_checklist_record_finisher FOREIGN KEY (finisher_id) REFERENCES tb_user,
    CONSTRAINT uk_checklist_record_flow_template UNIQUE (flow_id, template_id),
    CONSTRAINT ck_checklist_record_status CHECK (status IN ('DRAFT', 'IN_PROGRESS', 'PENDING', 'FINISHED', 'CANCELLED'))
);

CREATE TABLE tb_checklist_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    reason TEXT NOT NULL,
    snapshot_json TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_revision_record FOREIGN KEY (record_id) REFERENCES tb_checklist_record ON DELETE CASCADE,
    CONSTRAINT fk_checklist_revision_user FOREIGN KEY (created_by) REFERENCES tb_user
);

CREATE TABLE tb_checklist_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    problem_id VARCHAR(120),
    content TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_comment_record FOREIGN KEY (record_id) REFERENCES tb_checklist_record ON DELETE CASCADE,
    CONSTRAINT fk_checklist_comment_user FOREIGN KEY (author_id) REFERENCES tb_user
);

CREATE TABLE tb_checklist_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL,
    actor_id BIGINT,
    actor_name VARCHAR(255) NOT NULL,
    action VARCHAR(80) NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_audit_record FOREIGN KEY (record_id) REFERENCES tb_checklist_record ON DELETE CASCADE,
    CONSTRAINT fk_checklist_audit_user FOREIGN KEY (actor_id) REFERENCES tb_user
);

CREATE TABLE tb_checklist_catalog_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_catalog_user FOREIGN KEY (created_by) REFERENCES tb_user,
    CONSTRAINT uk_checklist_catalog_name UNIQUE (type, normalized_name),
    CONSTRAINT ck_checklist_catalog_type CHECK (type IN ('ITEM', 'DEFECT'))
);

ALTER TABLE tb_stepflow_order ADD COLUMN checklist_integration BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tb_stepflow_order_step ADD COLUMN checklist_pending BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tb_stepflow_order ALTER COLUMN checklist_integration SET DEFAULT TRUE;

CREATE TABLE tb_checklist_step_requirement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_type VARCHAR(40) NOT NULL,
    category_id BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_checklist_step_requirement_type UNIQUE (step_type),
    CONSTRAINT fk_checklist_step_requirement_category FOREIGN KEY (category_id) REFERENCES tb_checklist_category,
    CONSTRAINT fk_checklist_step_requirement_user FOREIGN KEY (updated_by) REFERENCES tb_user
);

CREATE TABLE tb_checklist_step_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    flow_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_step_binding_order FOREIGN KEY (order_id) REFERENCES tb_stepflow_order ON DELETE CASCADE,
    CONSTRAINT fk_checklist_step_binding_flow FOREIGN KEY (flow_id) REFERENCES tb_checklist_flow,
    CONSTRAINT fk_checklist_step_binding_user FOREIGN KEY (created_by) REFERENCES tb_user,
    CONSTRAINT uk_checklist_step_binding UNIQUE (order_id, flow_id)
);

CREATE INDEX idx_checklist_template_category ON tb_checklist_template(category_id, display_order);
CREATE INDEX idx_checklist_record_status_updated ON tb_checklist_record(status, updated_at DESC);
CREATE INDEX idx_checklist_record_owner ON tb_checklist_record(owner_id, status);
CREATE INDEX idx_checklist_record_flow ON tb_checklist_record(flow_id);
CREATE INDEX idx_checklist_comment_record ON tb_checklist_comment(record_id, created_at);
CREATE INDEX idx_checklist_audit_record ON tb_checklist_audit(record_id, created_at);
CREATE INDEX idx_checklist_flow_client ON tb_checklist_flow(client_id);
CREATE INDEX idx_checklist_step_binding_flow ON tb_checklist_step_binding(flow_id);

INSERT INTO tb_checklist_catalog_entry (type, name, normalized_name)
VALUES
    ('ITEM', 'Adesivo', 'adesivo'),
    ('ITEM', 'Alarme sonoro', 'alarme sonoro'),
    ('ITEM', 'Arruelas', 'arruelas'),
    ('ITEM', 'Barra chata', 'barra chata'),
    ('ITEM', 'Barra roscada', 'barra roscada'),
    ('ITEM', 'Batentes', 'batentes'),
    ('ITEM', 'Botão de emergencia', 'botão de emergencia'),
    ('ITEM', 'Braço', 'braço'),
    ('ITEM', 'Bucha', 'bucha'),
    ('ITEM', 'Calço de acionamento', 'calço de acionamento'),
    ('ITEM', 'Calço de segurança', 'calço de segurança'),
    ('ITEM', 'Cantoneira', 'cantoneira'),
    ('ITEM', 'Capturas', 'capturas'),
    ('ITEM', 'Cartucho', 'cartucho'),
    ('ITEM', 'Cavalete', 'cavalete'),
    ('ITEM', 'Ch proteção lateral', 'ch proteção lateral'),
    ('ITEM', 'Chapa de fixação', 'chapa de fixação'),
    ('ITEM', 'Chapa para choque', 'chapa para choque'),
    ('ITEM', 'Chapa traseira', 'chapa traseira'),
    ('ITEM', 'Chave seletora', 'chave seletora'),
    ('ITEM', 'Checklist', 'checklist'),
    ('ITEM', 'Chumbadores', 'chumbadores'),
    ('ITEM', 'Cilindro', 'cilindro'),
    ('ITEM', 'Cj quadro de sustentação', 'cj quadro de sustentação'),
    ('ITEM', 'Comandos eletronicos', 'comandos eletronicos'),
    ('ITEM', 'Componentes', 'componentes'),
    ('ITEM', 'Comunicação interna', 'comunicação interna'),
    ('ITEM', 'Conexão hidráulica', 'conexão hidráulica'),
    ('ITEM', 'Controle', 'controle'),
    ('ITEM', 'Cupilhas', 'cupilhas'),
    ('ITEM', 'Danificados na pintura', 'danificados na pintura'),
    ('ITEM', 'Eixo', 'eixo'),
    ('ITEM', 'Embalagem', 'embalagem'),
    ('ITEM', 'Fixadores', 'fixadores'),
    ('ITEM', 'Fonte', 'fonte'),
    ('ITEM', 'Fosso', 'fosso'),
    ('ITEM', 'Gabarito', 'gabarito'),
    ('ITEM', 'Guarda corpo', 'guarda corpo'),
    ('ITEM', 'Jaqueta cone', 'jaqueta cone'),
    ('ITEM', 'Kit', 'kit'),
    ('ITEM', 'Luminárias', 'luminárias'),
    ('ITEM', 'Mancal', 'mancal'),
    ('ITEM', 'Mangueira', 'mangueira'),
    ('ITEM', 'Manipulo', 'manipulo'),
    ('ITEM', 'Manual', 'manual'),
    ('ITEM', 'Material sobressalente', 'material sobressalente'),
    ('ITEM', 'Mecanismo hidraulico', 'mecanismo hidraulico'),
    ('ITEM', 'Mola a gás', 'mola a gás'),
    ('ITEM', 'Mola helicoidal', 'mola helicoidal'),
    ('ITEM', 'Moskit', 'moskit'),
    ('ITEM', 'Motor', 'motor'),
    ('ITEM', 'N° série', 'n° série'),
    ('ITEM', 'Niveladora', 'niveladora'),
    ('ITEM', 'Óleo hidraulico', 'óleo hidraulico'),
    ('ITEM', 'Olhal', 'olhal'),
    ('ITEM', 'Painel de acionamento', 'painel de acionamento'),
    ('ITEM', 'Palete', 'palete'),
    ('ITEM', 'Parachoque', 'parachoque'),
    ('ITEM', 'Parafuso', 'parafuso'),
    ('ITEM', 'Pé de apoio', 'pé de apoio'),
    ('ITEM', 'Pedestal', 'pedestal'),
    ('ITEM', 'Pedido', 'pedido'),
    ('ITEM', 'Perfil', 'perfil'),
    ('ITEM', 'Pestana', 'pestana'),
    ('ITEM', 'Placa eletronica', 'placa eletronica'),
    ('ITEM', 'Plaqueta identificação', 'plaqueta identificação'),
    ('ITEM', 'Plataforma', 'plataforma'),
    ('ITEM', 'Porca', 'porca'),
    ('ITEM', 'Porta seccional', 'porta seccional'),
    ('ITEM', 'Projeto', 'projeto'),
    ('ITEM', 'Quadro de comando', 'quadro de comando'),
    ('ITEM', 'Rolamento', 'rolamento'),
    ('ITEM', 'Suporte barra antiesmagamento', 'suporte barra antiesmagamento'),
    ('ITEM', 'Suporte barra contra peso', 'suporte barra contra peso'),
    ('ITEM', 'Suporte do calço de segurança', 'suporte do calço de segurança'),
    ('ITEM', 'Suporte do mancal', 'suporte do mancal'),
    ('ITEM', 'Suporte do motor', 'suporte do motor'),
    ('ITEM', 'Suporte do sistema hidraulico', 'suporte do sistema hidraulico'),
    ('ITEM', 'Suporte guarda corpo', 'suporte guarda corpo'),
    ('ITEM', 'Suporte içamento', 'suporte içamento'),
    ('ITEM', 'Suporte lateral', 'suporte lateral'),
    ('ITEM', 'Suporte manipulo', 'suporte manipulo'),
    ('ITEM', 'Suporte pestana', 'suporte pestana'),
    ('ITEM', 'Suporte prender corrente', 'suporte prender corrente'),
    ('ITEM', 'Transdutores do semaforo', 'transdutores do semaforo'),
    ('ITEM', 'Trava pestana', 'trava pestana'),
    ('ITEM', 'Unidade hidraulica', 'unidade hidraulica'),
    ('ITEM', 'Valvula solenoide', 'valvula solenoide'),
    ('ITEM', 'Voltagem', 'voltagem'),
    ('DEFECT', 'Acabamento deficiente', 'acabamento deficiente'),
    ('DEFECT', 'Cantos vivos/cortantes', 'cantos vivos/cortantes'),
    ('DEFECT', 'Caroço de solda', 'caroço de solda'),
    ('DEFECT', 'Checklist incompleto', 'checklist incompleto'),
    ('DEFECT', 'Checklist perdido', 'checklist perdido'),
    ('DEFECT', 'Com vazamento', 'com vazamento'),
    ('DEFECT', 'Componente danificado', 'componente danificado'),
    ('DEFECT', 'Deformado', 'deformado'),
    ('DEFECT', 'Desalinhado', 'desalinhado'),
    ('DEFECT', 'Descentralizado', 'descentralizado'),
    ('DEFECT', 'Descolando', 'descolando'),
    ('DEFECT', 'Empenado', 'empenado'),
    ('DEFECT', 'Equipamento com sujeira', 'equipamento com sujeira'),
    ('DEFECT', 'Erro de informação', 'erro de informação'),
    ('DEFECT', 'Erro de projeto', 'erro de projeto'),
    ('DEFECT', 'Erro de separação', 'erro de separação'),
    ('DEFECT', 'Falta chanfro', 'falta chanfro'),
    ('DEFECT', 'Falta componente', 'falta componente'),
    ('DEFECT', 'Falta informação', 'falta informação'),
    ('DEFECT', 'Fora de posição', 'fora de posição'),
    ('DEFECT', 'Fora do esquadro', 'fora do esquadro'),
    ('DEFECT', 'Funcionamento irregular', 'funcionamento irregular'),
    ('DEFECT', 'Furação desalinhada', 'furação desalinhada'),
    ('DEFECT', 'Incompleto', 'incompleto'),
    ('DEFECT', 'Lixamento em excesso', 'lixamento em excesso'),
    ('DEFECT', 'Mau funcionamento', 'mau funcionamento'),
    ('DEFECT', 'Não conforme pedido', 'não conforme pedido'),
    ('DEFECT', 'Não conforme projeto', 'não conforme projeto'),
    ('DEFECT', 'Não seguir procedimentos internos', 'não seguir procedimentos internos'),
    ('DEFECT', 'Oxidando', 'oxidando'),
    ('DEFECT', 'Parafuso frouxo', 'parafuso frouxo'),
    ('DEFECT', 'Pintura com camada baixa', 'pintura com camada baixa'),
    ('DEFECT', 'Pintura com sujeira', 'pintura com sujeira'),
    ('DEFECT', 'Pintura danificada', 'pintura danificada'),
    ('DEFECT', 'Pintura deficiente, com falhas', 'pintura deficiente, com falhas'),
    ('DEFECT', 'Pintura desplacando', 'pintura desplacando'),
    ('DEFECT', 'Pintura escorrida', 'pintura escorrida'),
    ('DEFECT', 'Queimado', 'queimado'),
    ('DEFECT', 'Rebarbas', 'rebarbas'),
    ('DEFECT', 'Respingos de solda', 'respingos de solda'),
    ('DEFECT', 'Sobra de arame', 'sobra de arame'),
    ('DEFECT', 'Sobra de material', 'sobra de material'),
    ('DEFECT', 'Solda com excesso de penetração/perfuração da chapa', 'solda com excesso de penetração/perfuração da chapa'),
    ('DEFECT', 'Solda com mal aspecto', 'solda com mal aspecto'),
    ('DEFECT', 'Solda com mordedura', 'solda com mordedura'),
    ('DEFECT', 'Solda com porosidade', 'solda com porosidade'),
    ('DEFECT', 'Solda com trincas', 'solda com trincas'),
    ('DEFECT', 'Solda faltando', 'solda faltando'),
    ('DEFECT', 'Solda fora de posição', 'solda fora de posição'),
    ('DEFECT', 'Solda insuficiente', 'solda insuficiente'),
    ('DEFECT', 'Solda sem penetração', 'solda sem penetração'),
    ('DEFECT', 'Mal fixado', 'mal fixado');

CREATE TABLE tb_checklist_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL,
    problem_id VARCHAR(120) NOT NULL,
    picture_id BIGINT,
    video_id BIGINT,
    original_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(160) NOT NULL,
    size BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_evidence_record FOREIGN KEY (record_id) REFERENCES tb_checklist_record ON DELETE CASCADE,
    CONSTRAINT fk_checklist_evidence_picture FOREIGN KEY (picture_id) REFERENCES tb_picture,
    CONSTRAINT fk_checklist_evidence_video FOREIGN KEY (video_id) REFERENCES tb_video,
    CONSTRAINT fk_checklist_evidence_user FOREIGN KEY (created_by) REFERENCES tb_user,
    CONSTRAINT uk_checklist_evidence_picture UNIQUE (picture_id),
    CONSTRAINT uk_checklist_evidence_video UNIQUE (video_id),
    CONSTRAINT ck_checklist_evidence_media CHECK ((picture_id IS NOT NULL AND video_id IS NULL) OR (picture_id IS NULL AND video_id IS NOT NULL))
);

CREATE INDEX idx_checklist_evidence_record_problem ON tb_checklist_evidence(record_id, problem_id, created_at);

