CREATE TABLE tb_event (
    created_at TIMESTAMP WITH TIME ZONE,
    event_date TIMESTAMP WITH TIME ZONE,
    picture_id BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    title VARCHAR(255),
    PRIMARY KEY (picture_id)
);

CREATE TABLE tb_file (
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_name VARCHAR(255),
    title VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tb_memorando (
    create_at TIMESTAMP WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    number BIGINT,
    request BIGINT,
    user_id BIGINT,
    client VARCHAR(255),
    description TEXT,
    reason TEXT,
    title VARCHAR(255),
    items VARCHAR(255) ARRAY,
    status VARCHAR(32),
    PRIMARY KEY (id)
);

CREATE TABLE tb_memorando_departments (
    departments_id BIGINT NOT NULL,
    memorando_id BIGINT NOT NULL
);

CREATE TABLE tb_memorando_log (
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    memorando_id BIGINT,
    user_id BIGINT,
    content VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tb_notification (
    auto_delete BOOLEAN NOT NULL,
    viewed BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by_user_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reference_id BIGINT,
    user_id BIGINT,
    action_url VARCHAR(255),
    message VARCHAR(255),
    type VARCHAR(32),
    PRIMARY KEY (id)
);

CREATE TABLE tb_param (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(255),
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tb_picture (
    created_at TIMESTAMP WITH TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT,
    step_id BIGINT,
    name VARCHAR(255),
    path VARCHAR(255),
    size VARCHAR(255),
    type VARCHAR(32),
    PRIMARY KEY (id)
);

CREATE TABLE tb_position (
    activated BOOLEAN,
    is_locked BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tb_position_manangers (
    mananger_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    PRIMARY KEY (mananger_id, position_id)
);

CREATE TABLE tb_post (
    is_warning BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id BIGINT,
    content TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE tb_role (
    father_id BIGINT UNIQUE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    authority VARCHAR(255) UNIQUE,
    parent VARCHAR(255),
    parent_url VARCHAR(255),
    title VARCHAR(255),
    title_url VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tb_signature (
    is_sign BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    memorando_id BIGINT NOT NULL,
    position_signed_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (memorando_id, position_signed_id, user_id)
);

CREATE TABLE tb_stepflow_order (
    discount FLOAT(53),
    due_date DATE,
    number INTEGER,
    shipment FLOAT(53),
    start_date DATE,
    subtotal FLOAT(53),
    total FLOAT(53),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    address VARCHAR(255),
    carrier VARCHAR(255),
    client VARCHAR(255),
    cnpj VARCHAR(255),
    phone VARCHAR(255),
    seller VARCHAR(255),
    current_step VARCHAR(32),
    status VARCHAR(32),
    PRIMARY KEY (id)
);

CREATE TABLE tb_stepflow_order_item (
    produced_quantity INTEGER,
    quantity INTEGER,
    total FLOAT(53),
    unit_price FLOAT(53),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT,
    description VARCHAR(255),
    item_code VARCHAR(255),
    unit VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tb_stepflow_order_step (
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    finished_by_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT,
    started_at TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(32),
    step VARCHAR(32),
    PRIMARY KEY (id)
);

CREATE TABLE tb_stepflow_step_message (
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    step_id BIGINT,
    message TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE tb_stepflow_video (
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_step_id BIGINT,
    bunny_video_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    view_url VARCHAR(255),
    status VARCHAR(32),
    PRIMARY KEY (id)
);

CREATE TABLE tb_user (
    activated BOOLEAN,
    birth_date DATE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    picture_id BIGINT UNIQUE,
    position_id BIGINT,
    update_at TIMESTAMP WITHOUT TIME ZONE,
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    support_token VARCHAR(255),
    username VARCHAR(255) UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE tb_user_role (
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, user_id)
);

ALTER TABLE tb_event
    ADD CONSTRAINT fk_event_picture FOREIGN KEY (picture_id) REFERENCES tb_picture;
ALTER TABLE tb_memorando
    ADD CONSTRAINT fk_memorando_user FOREIGN KEY (user_id) REFERENCES tb_user;
ALTER TABLE tb_memorando_departments
    ADD CONSTRAINT fk_memorando_department_position FOREIGN KEY (departments_id) REFERENCES tb_position;
ALTER TABLE tb_memorando_departments
    ADD CONSTRAINT fk_memorando_department_memorando FOREIGN KEY (memorando_id) REFERENCES tb_memorando;
ALTER TABLE tb_memorando_log
    ADD CONSTRAINT fk_memorando_log_memorando FOREIGN KEY (memorando_id) REFERENCES tb_memorando;
ALTER TABLE tb_memorando_log
    ADD CONSTRAINT fk_memorando_log_user FOREIGN KEY (user_id) REFERENCES tb_user;
ALTER TABLE tb_notification
    ADD CONSTRAINT fk_notification_created_by FOREIGN KEY (created_by_user_id) REFERENCES tb_user;
ALTER TABLE tb_notification
    ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES tb_user;
ALTER TABLE tb_picture
    ADD CONSTRAINT fk_picture_step FOREIGN KEY (step_id) REFERENCES tb_stepflow_order_step;
ALTER TABLE tb_picture
    ADD CONSTRAINT fk_picture_post FOREIGN KEY (post_id) REFERENCES tb_post;
ALTER TABLE tb_position_manangers
    ADD CONSTRAINT fk_position_manager_user FOREIGN KEY (mananger_id) REFERENCES tb_user;
ALTER TABLE tb_position_manangers
    ADD CONSTRAINT fk_position_manager_position FOREIGN KEY (position_id) REFERENCES tb_position;
ALTER TABLE tb_post
    ADD CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES tb_user;
ALTER TABLE tb_role
    ADD CONSTRAINT fk_role_father FOREIGN KEY (father_id) REFERENCES tb_role;
ALTER TABLE tb_signature
    ADD CONSTRAINT fk_signature_position FOREIGN KEY (position_signed_id) REFERENCES tb_position;
ALTER TABLE tb_signature
    ADD CONSTRAINT fk_signature_memorando FOREIGN KEY (memorando_id) REFERENCES tb_memorando;
ALTER TABLE tb_signature
    ADD CONSTRAINT fk_signature_user FOREIGN KEY (user_id) REFERENCES tb_user;
ALTER TABLE tb_stepflow_order_item
    ADD CONSTRAINT fk_stepflow_item_order FOREIGN KEY (order_id) REFERENCES tb_stepflow_order;
ALTER TABLE tb_stepflow_order_step
    ADD CONSTRAINT fk_stepflow_step_finished_by FOREIGN KEY (finished_by_id) REFERENCES tb_user;
ALTER TABLE tb_stepflow_order_step
    ADD CONSTRAINT fk_stepflow_step_order FOREIGN KEY (order_id) REFERENCES tb_stepflow_order;
ALTER TABLE tb_stepflow_step_message
    ADD CONSTRAINT fk_stepflow_message_created_by FOREIGN KEY (created_by) REFERENCES tb_user;
ALTER TABLE tb_stepflow_step_message
    ADD CONSTRAINT fk_stepflow_message_step FOREIGN KEY (step_id) REFERENCES tb_stepflow_order_step;
ALTER TABLE tb_stepflow_video
    ADD CONSTRAINT fk_stepflow_video_step FOREIGN KEY (order_step_id) REFERENCES tb_stepflow_order_step;
ALTER TABLE tb_user
    ADD CONSTRAINT fk_user_picture FOREIGN KEY (picture_id) REFERENCES tb_picture;
ALTER TABLE tb_user
    ADD CONSTRAINT fk_user_position FOREIGN KEY (position_id) REFERENCES tb_position;
ALTER TABLE tb_user_role
    ADD CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES tb_role;
ALTER TABLE tb_user_role
    ADD CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES tb_user;
