CREATE TABLE tb_raw_material_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    conversion_factor TEXT,
    dimension_fields TEXT NOT NULL DEFAULT 'length,width,thickness,height,weightPerSquareMeter,litersPerUnit,weightPerLinearMeter',
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_raw_material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    current_storage NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (current_storage >= 0),
    min_storage NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (min_storage >= 0),
    max_storage NUMERIC(18,3) NOT NULL DEFAULT 0,
    length NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (length >= 0),
    width NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (width >= 0),
    thickness NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (thickness >= 0),
    height NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (height >= 0),
    weight_per_square_meter NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (weight_per_square_meter >= 0),
    liters_per_unit NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (liters_per_unit >= 0),
    weight_per_linear_meter NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (weight_per_linear_meter >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_raw_material_category FOREIGN KEY (category_id) REFERENCES tb_raw_material_category,
    CONSTRAINT fk_raw_material_updated_by FOREIGN KEY (updated_by) REFERENCES tb_user,
    CONSTRAINT ck_raw_material_storage_range CHECK (min_storage = 0 OR max_storage = 0 OR max_storage >= min_storage)
);

CREATE INDEX idx_raw_material_category_active ON tb_raw_material(category_id, active);
CREATE INDEX idx_raw_material_name ON tb_raw_material(name);
CREATE INDEX idx_raw_material_updated_at ON tb_raw_material(updated_at DESC);

CREATE TABLE tb_raw_material_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_material_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    action VARCHAR(40) NOT NULL,
    previous_storage NUMERIC(18,3),
    new_storage NUMERIC(18,3),
    changed_fields VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_raw_material_history_item FOREIGN KEY (raw_material_id) REFERENCES tb_raw_material ON DELETE CASCADE,
    CONSTRAINT fk_raw_material_history_user FOREIGN KEY (created_by) REFERENCES tb_user
);

CREATE INDEX idx_raw_material_history_item_date ON tb_raw_material_history(raw_material_id, created_at DESC, id DESC);

CREATE TABLE tb_raw_material_category_access (
    category_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (category_id, user_id),
    CONSTRAINT fk_raw_material_category_access_category FOREIGN KEY (category_id) REFERENCES tb_raw_material_category ON DELETE CASCADE,
    CONSTRAINT fk_raw_material_category_access_user FOREIGN KEY (user_id) REFERENCES tb_user ON DELETE CASCADE
);

INSERT INTO tb_param (name, content)
SELECT 'rawMaterialsHistoryRetention', '1000'
WHERE NOT EXISTS (SELECT 1 FROM tb_param WHERE name = 'rawMaterialsHistoryRetention');

INSERT INTO tb_raw_material_category (name)
SELECT 'Chapas Finas' WHERE NOT EXISTS (SELECT 1 FROM tb_raw_material_category WHERE name = 'Chapas Finas');
INSERT INTO tb_raw_material_category (name, conversion_factor)
SELECT 'Aços Longos', '%c * %p' WHERE NOT EXISTS (SELECT 1 FROM tb_raw_material_category WHERE name = 'Aços Longos');
INSERT INTO tb_raw_material_category (name)
SELECT 'Pallet' WHERE NOT EXISTS (SELECT 1 FROM tb_raw_material_category WHERE name = 'Pallet');

-- Compatibilidade com usuários que já possuíam apenas a permissão raiz antes
-- da criação dos níveis de acesso: tornam-se operadores, preservando o acesso.
INSERT INTO tb_user_role (user_id, role_id)
SELECT root_access.user_id, operator_role.id
FROM tb_user_role root_access
JOIN tb_role root_role ON root_role.id = root_access.role_id AND root_role.authority = 'ROLE_RAW_MATERIALS'
JOIN tb_role operator_role ON operator_role.authority = 'ROLE_RAW_MATERIALS_OPERATOR'
WHERE NOT EXISTS (
    SELECT 1 FROM tb_user_role access_level
    JOIN tb_role level_role ON level_role.id = access_level.role_id
    WHERE access_level.user_id = root_access.user_id
      AND level_role.authority IN ('ROLE_RAW_MATERIALS_ADMIN', 'ROLE_RAW_MATERIALS_OPERATOR', 'ROLE_RAW_MATERIALS_CONSULTATION')
);
