# Spring
spring.application.name=portal
spring.profiles.active=${APP_PROFILE:dev}
spring.jpa.open-in-view=false

# Segurança
security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}
security.jwt.duration=${JWT_DURATION:86400}
cors.origins=${CORS_ORIGINS:http://localhost:4200}

# Arquivos
app.server.image-path=${IMAGE_PATH:C:\\workspace\\outros\\imagens}
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
