# Conexao com o banco postgres
spring.datasource.url=${DATA_BASE:jdbc:postgresql://localhost:5432/db_portal}
spring.datasource.username=${DB_USER:consulta}
spring.datasource.password=${DB_PASSWORD:consulta}
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
