package br.com.metaro.portal.modules.quality.checklist;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.sql.DriverManager;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class ChecklistModuleMigrationTests {
    @Test
    void createsChecklistSchemaAndSeedsApprovedCatalogs() throws Exception {
        try (var connection = DriverManager.getConnection("jdbc:h2:mem:checklist-module-" + UUID.randomUUID());
            var statement = connection.createStatement()) {
            statement.execute("""
                CREATE TABLE tb_role (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    authority VARCHAR(255), title VARCHAR(255), title_url VARCHAR(255),
                    parent VARCHAR(255), parent_url VARCHAR(255),
                    father_id BIGINT REFERENCES tb_role(id), activated BOOLEAN
                )
                """);
            statement.execute("CREATE TABLE tb_user (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
            statement.execute("CREATE TABLE tb_picture (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
            statement.execute("CREATE TABLE tb_video (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
            statement.execute("CREATE TABLE tb_stepflow_order (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
            ScriptUtils.executeSqlScript(connection, new ClassPathResource("db/migration/V15__create_checklist_module.sql"));

            statement.execute("INSERT INTO tb_checklist_category (name, integration, document_title) VALUES ('Auditoria 5S', 'FIVE_S', 'Auditoria 5S')");

            try (var result = statement.executeQuery("SELECT COUNT(*) FROM tb_checklist_catalog_entry WHERE type = 'ITEM'")) {
                result.next();
                assertThat(result.getInt(1)).isEqualTo(89);
            }
            try (var result = statement.executeQuery("SELECT COUNT(*) FROM tb_checklist_catalog_entry WHERE type = 'DEFECT'")) {
                result.next();
                assertThat(result.getInt(1)).isEqualTo(52);
            }
            try (var result = statement.executeQuery("SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'TB_CHECKLIST_%'")) {
                result.next();
                assertThat(result.getInt(1)).isEqualTo(13);
            }
            try (var result = statement.executeQuery("SELECT COUNT(*) FROM tb_role WHERE authority LIKE 'ROLE_CHECKLIST%' AND activated = TRUE")) {
                result.next();
                assertThat(result.getInt(1)).isEqualTo(4);
            }
            try (var result = statement.executeQuery("SELECT parent_url, title_url FROM tb_role WHERE authority = 'ROLE_CHECKLIST'")) {
                result.next();
                assertThat(result.getString(1) + result.getString(2)).isEqualTo("/qualidade/checklist");
            }
            try (var result = statement.executeQuery("""
                    SELECT COUNT(*) FROM tb_role child JOIN tb_role parent ON child.father_id = parent.id
                    WHERE parent.authority = 'ROLE_CHECKLIST'
                    AND child.authority IN ('ROLE_CHECKLIST_ADMIN', 'ROLE_CHECKLIST_OPERATOR', 'ROLE_CHECKLIST_CONSULTATION')
                    """)) {
                result.next();
                assertThat(result.getInt(1)).isEqualTo(3);
            }
        }
    }
}
